# Generated by Django 3.2.8 on 2021-10-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0005_metrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrics',
            name='metric',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
